services:
  postgres:  # Configuración del contenedor PostgreSQL (la bace de datos)
    image: postgres:15 # Usa la imagen oficial de PostgreSQL versión 15.
    container_name: crm_postgres # Nombre personalizado del contenedor.
    restart: always # Reinicia automáticamente si falla o se reinicia el host.
    environment: # Variables de entorno para configurar PostgreSQL.
      POSTGRES_USER: postgres # Usuario por defecto (superusuario).
      POSTGRES_PASSWORD: postgres # Contraseña del usuario.
      POSTGRES_DB: crm_db # Base de datos creada al iniciar el contenedor.
    ports:
      - "5432:5432" # Mapea el puerto 5432 del contenedor al 5432 del host.
    volumes:
      - pgdata:/var/lib/postgresql/data # Monta el volumen `pgdata` para persistir datos.

  pgadmin:  # Configuración del contenedor pgAdmin (El administrador grafico de progres)
    image: dpage/pgadmin4 # Imagen oficial de pgAdmin 4.
    container_name: crm_pgadmin # Nombre personalizado del contenedor.
    restart: always # Reinicio automático.
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@crm.com # Email para iniciar sesión en pgAdmin.
      PGADMIN_DEFAULT_PASSWORD: admin # Contraseña para pgAdmin.
    ports:
      - "5050:80" # Mapea el puerto 80 del contenedor al 5050 del host.

volumes:
  pgdata:  # Volumen para persistir datos de PostgreSQL
